### ISSUE TITLE
RocketChat link doesn't work

### ISSUE THREAD

**Issue by JPABotermans** [crowdcent/numerblox#133]
Well, I think the title says it all :) 

<img width="594" alt="image" src="https://github.com/crowdcent/numerblox/assets/45882689/11669453-2e84-4135-820a-03454238d4ee">

**Comment by CarloLepelaars** [comment]
Hey, good catch! Numerai took the RocketChat down some time ago in favor of Discord. We don't have a separate NumerBlox channel there, but Discord is now where people are discussing Numerai.

Link to Numerai Discord:
https://discord.gg/numerai

Discord announcement:
https://forum.numer.ai/t/discord-the-next-chapter/6267

**Comment by crowdcent** [comment]
Removed RocketChat link in the new Numerblox v0.5.11 version.
