### ISSUE TITLE
Model Upload

### ISSUE THREAD

**Issue by jmrichardson** [crowdcent/numerblox#173]
Hi, 

I am enjoying using this package and makes things a lot easier to manage.  Especially like your new documentation too.  Quick question, will there be any integration with model upload?  Ie, take a model or ensemble of models that have just been trained and upload to numerai's model uploads repository?

**Comment by CarloLepelaars** [comment]
Hey @jmrichardson! You are referring to [this Model Uploads](https://docs.numer.ai/numerai-tournament/submissions/model-uploads), right? We are not using Model Uploads so I have no experience with it and also don't think @jrosenfeld13 has. 

We are always happy to accept PRs from the community with a good integration. Seems like it mostly comes down to making a custom `predict` function and saving the full pipeline with `cloudpickle`?

**Comment by jmrichardson** [comment]
Hi @CarloLepelaars 

Yes, your description is correct.  I am traveling for a bit but will take a look at potentially submitting a PR.  Thanks.
