### ISSUE TITLE
Submission failures

### ISSUE THREAD

**Issue by jrosenfeld13** [crowdcent/numerblox#49]
Add graceful failing for Submitter. Sometimes the API submission will fail (but succeed on a retry). In a submission loop for multiple models, it would be helpful to retry submissions or move onto the next model, failing "gracefully" and notifying end user.

**Comment by CarloLepelaars** [comment]
This will be solved in NumerBlox 1.0.

`upload_predictions` in a submitter will try uploading multiple times with set time interval in between. By default it will try 2 times with a 10 second delay. This can be customised by setting `max_retries` and `sleep_time` when initializing a submitter. 

Additionally you have the option the skip the prediction uploading without throwing an error by setting `fail_silently=True` when initializing a submitter. Especially handy for if you are running a submission loop for multiple models.

New upload predictions function:
https://github.com/crowdcent/numerblox/blob/55c156f81d05c06ba1625f9841d372dac5232531/numerblox/submission.py#L50
