### ISSUE TITLE
Numerai dataset versioning breaking changes

### ISSUE THREAD

**Issue by crowdcent** [crowdcent/numerblox#56]
There seems to be a new data versioning structure for datasets accompanying the new [v4 dataset release](https://forum.numer.ai/t/v4-tournament-data-announcement/5163). `NumeraiClassicDownloader` and applications of it should be adjusted to support this new versioning. Should be a small fix if we adjust the version mapping in `NumeraiClassicDownloader`.
![breaking_numerapi](https://user-images.githubusercontent.com/64117634/160660196-b96ffdc0-6978-4786-85fa-1e195c48d30b.png)

**Comment by CarloLepelaars** [comment]
Fixed for v0.2.7.
