### ISSUE TITLE
FNCv3: Fall back on "v3/medium" if v4/fncv3_features feature set not present.

### ISSUE THREAD

**Issue by crowdcent** [crowdcent/numerblox#75]
Currently, `NumeraiClassicEvaluator` checks if all features from the `v3/features.json/medium` feature set used to calculate FNCv3 are present in the input `NumerFrame`.  Else, it will skip computing FNCv3. 

However, Numerai also provides us with `v4/features.json/fncv3_features`. This is a feature set present in [v4 data](https://numer.ai/data/v4) that closely approximates the medium feature set. 

All feature sets are defined in `features.json` downloadable through `numerapi`.

**Fallback approach for computing FNCv3:**
1. Check if columns in `v4/features.json/fncv3_features` feature set are present.
2. If not, check if features in `v3/features.json/medium` are present.
3. If not, skip computation of FNCv3. Provide user with clear message that not enough features are present in input `NumerFrame` to compute FNCv3.

`numerblox` Evaluator docs:
https://crowdcent.github.io/numerblox/evaluation.html#Overview

**Comment by michael-phillips-data** [comment]
I'd suggest using the v4/features.json feature_set called `fncv3_features`, which contains the 420 features used for calculating FNCv3.

The `v3_equivalent_features` contains all 1050 of the features found in the v3 dataset, so that would be significantly different from the FNCv3 calculation which only uses 420 of them

**Comment by CarloLepelaars** [comment]
Ok, thanks for the heads up @michael-phillips-data! Do `fncv3_features` and `medium` contain exactly the same features? In that case we probably don't need fallback and can just check only if `fncv3_features` are present, regardless if v3 or v4 data is used.

**Comment by michael-phillips-data** [comment]
`v4/features.json/fncv3_features` and `v3/features.json/medium_features` are the same.   But `v4/features.json/medium` contains extra features that weren't in the v3 dataset at all

**Comment by crowdcent** [comment]
Solved by #76

**Comment by crowdcent** [comment]
Added in new release (v0.2.13)
https://github.com/crowdcent/numerblox/releases/tag/v0.2.13
